packages:
    - 'apps/*'
    - 'libs/*'
    - 'packages/*'
    - 'docs'
catalogs:
    angular22:
        '@angular/build': ~22.0.6
        '@angular/cli': ~22.0.6
        '@angular/common': ~22.0.6
        '@angular/compiler': ~22.0.6
        '@angular/compiler-cli': ~22.0.6
        '@angular/core': ~22.0.6
        '@angular/forms': ~22.0.6
        '@angular/platform-browser': ~22.0.6
        '@schematics/angular': ~22.0.6
        angular-eslint: ^22.1.0
        ng-packagr: ~22.0.1
        rxjs: ~7.8.0
        zone.js: ~0.15.0
    toolchain:
        typescript: ~6.0.3
    react19:
        '@types/react': 19.2.17
        '@types/react-dom': 19.2.3
        react: 19.2.7
        react-dom: 19.2.7
    vue3:
        '@vitejs/plugin-vue': ^6.0.8
        vue: ^3.5.40
    vite6:
        '@vitejs/plugin-react': ^4.2.0
        vite: ^6.0.0
        vite-plugin-dts: ~4.5.0
        vite-plugin-static-copy: ^3.1.0
        vite-tsconfig-paths: ^6.1.1
allowBuilds:
    '@parcel/watcher': true
    '@swc/core': true
    esbuild: true
    lmdb: true
    msgpackr-extract: true
    puppeteer: true
linkWorkspacePackages: true
minimumReleaseAge: 0
